server:
  port: 8686
  error:
    include-message: always
    include-exception: true
jwt:
  secret: ok9k49j4mkdl21cel
  lifetime: 30m

spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/todo_db
    username: postgres
    password: 1324
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    liquibase-schema: public
    database-change-log-lock-table: todo_lock
    database-change-log-table: todo_log
    change-log: classpath:db/changelog.yaml

springdoc:
  packages-to-scan: org.example.todoapp.controllers
  api-docs:
    enabled: true

logging:
  level:
    root: info
  file:
    name: app-logs
    path: /
