CREATE TABLE IF NOT EXISTS items (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    done BOOLEAN DEFAULT FALSE,
    list_id BIGINT NOT NULL,
    FOREIGN KEY (list_id) REFERENCES lists (id)
)